name: Build and Deploy
on:
  push:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0 ## replace by latest version without it you will see Expected format {org}/{repo}[/path]@ref. Actual 'AhsanAyaz/angular-deploy-gh-pages-actions',Input string was not in a correct format.
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }} 
        build_configuration: production
        angular_project_dir: ./website/
        deploy_branch: gh-pages
        angular_dist_build_folder: website/dist/website/browser # The folder where your project is supposed to be after running ng build by the action.
  
  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  
permissions:
  contents: write # Allow write permission to GITHUB_TOKEN to commit to deploy branch.
